name: CI/CD Pipeline

on:
  push:
    branches: [main, dev, develop, "dev-*"]
  pull_request:
    branches: [main, dev, develop, "dev-*"]

jobs:
  typecheck:
    name: TypeScript Compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install --frozen-lockfile
      - run: yarn compile

  lint:
    name: Lint (ESLint)
    runs-on: ubuntu-latest
    needs: typecheck
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install --frozen-lockfile
      - run: yarn lint

  build:
    name: Build (Lit)
    runs-on: ubuntu-latest
    needs: typecheck
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install --frozen-lockfile
      - run: yarn build:lit

  storybook:
    name: Build Storybook
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install --frozen-lockfile
      - run: yarn build-storybook

  chromatic:
    name: Chromatic Visual Regression
    runs-on: ubuntu-latest
    needs: storybook
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install --frozen-lockfile
      - name: Publish to Chromatic
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  a11y:
    name: Accessibility (pa11y)
    runs-on: ubuntu-latest
    needs: storybook
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install --frozen-lockfile
      - run: yarn build-storybook
      - name: Install static server
        run: yarn global add serve
      - name: Start Storybook static server
        run: serve -s storybook-static -l 6006 &
      - name: Wait for Storybook to be ready
        run: npx wait-on http://localhost:6006
      - name: Install Chromium
        run: sudo apt-get update && sudo apt-get install -y chromium-browser
      - name: Run pa11y-ci
        run: npx pa11y-ci http://localhost:6006
        env:
          PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium-browser"
          PUPPETEER_ARGS: "--no-sandbox --disable-setuid-sandbox"

  performance:
    name: Performance Budgets (Lighthouse)
    runs-on: ubuntu-latest
    needs: storybook
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install --frozen-lockfile
      - run: yarn build-storybook
      - name: Install static server
        run: yarn global add serve
      - name: Run Lighthouse CI
        run: npx lhci autorun --config=./lighthouserc.json

  cross-browser:
    name: Cross-Browser Tests (Playwright)
    runs-on: ubuntu-latest
    needs: storybook
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install --frozen-lockfile
      - run: yarn build-storybook
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Install static server
        run: yarn global add serve
      - name: Start Storybook static server
        run: serve -s storybook-static -l 6006 &
      - name: Wait for Storybook to be ready
        run: npx wait-on http://localhost:6006
      - name: Run Playwright tests
        run: yarn test:e2e
